---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - sudo
        - tmux
        - vim
        - tldr
        - git
        - nmap
        - rsync
        - tree

        
