---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - sudo
        - tmux
        - vim
        - apropos
        - tldr
        - git
        - nmap
        - rsync
        - tree
        - python3
        - python3-pip
  
  - name: ansible-personal service file creation
    copy: 
      src: ~/dev/ansible-personal/files/ansible-personal.service
      dest: /etc/systemd/user/ansible-personal.service
      owner: root
      group: root
      mode: 0440

  - name: ansible-personal timer file creation
    copy: 
      src: ~/dev/ansible-personal/files/ansible-personal.timer
      dest: /etc/systemd/user/ansible-personal.timer
      owner: root
      group: root
      mode: 0440

  - name: enable and unmask ansible-personal service
    systemd:
      name: ansible-personal.timer
      enabled: yes
      masked: no
